# Generated by Django 6.0 on 2026-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_options_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupquestion',
            name='path_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='path_count',
            field=models.IntegerField(default=0),
        ),
    ]
